'use client';

import { useState } from 'react';
import { Dice5, Lock, Palette, Play, Settings2, Volume2, X } from 'lucide-react';
import './monopoly.css';

type View = 'home' | 'lobby' | 'board' | 'dashboard';
type Space = { my:string; en:string; color?:string; icon?:string };

const spaces: Space[] = [
  ['စတင်နေရာ','START',undefined,'▶'],['မြစ်ကြီးနား','Myitkyina','#804eb6'],['ကံ','CHANCE',undefined,'✦'],['ကုန်သွယ်ခွန်','TRADE TAX',undefined,'₭'],['မြန်မာ့မီးရထား','TRANSPORT',undefined,'♜'],['ဗန်းမော်','Bhamo','#804eb6'],['လားရှိုး','Lashio','#804eb6'],['ရွှေဘို','Shwebo','#ec678d'],['လျှပ်စစ်ဝန်ဆောင်မှု','UTILITY',undefined,'⚡'],['စစ်ကိုင်း','Sagaing','#ec678d'],['အကျဉ်းစခန်း','JAIL',undefined,'⛓'],['မုံရွာ','Monywa','#ec678d'],['ငွေဆောင်','Ngwe Saung','#ea943a'],['ချောင်းသာ','Chaung Tha','#ea943a'],['အဝေးပြေးယာဉ်','TRANSPORT',undefined,'♜'],['ကြက်မောက်ကျွန်း','Chetthaung','#ea943a'],['ပဲခူး','Bago','#d85a5a'],['ကံ','CHANCE',undefined,'✦'],['တောင်ငူ','Taungoo','#d85a5a'],['ပြည်','Pyay','#d85a5a'],['အခမဲ့နားနေရာ','FREE PARKING',undefined,'⌘'],['မကွေး','Magway','#e4c249'],['ပဟေဠိ','PUZZLE',undefined,'?'],['မင်းဘူး','Minbu','#e4c249'],['လေကြောင်းခရီး','TRANSPORT',undefined,'♜'],['နေပြည်တော်','Nay Pyi Taw','#e4c249'],['မိတ္ထီလာ','Meiktila','#54a768'],['ရေပေးဝေရေး','UTILITY',undefined,'◈'],['ပြင်ဦးလွင်','Pyin Oo Lwin','#54a768'],['မန္တလေး','Mandalay','#54a768'],['အကျဉ်းစခန်းသို့ သွားပါ','GO TO JAIL',undefined,'⛓'],['ကလော','Kalaw','#408ec7'],['ပဟေဠိ','PUZZLE',undefined,'?'],['အင်းလေး','Inle','#408ec7'],['မြစ်ကြောင်းခရီး','TRANSPORT',undefined,'♜'],['တောင်ကြီး','Taunggyi','#408ec7'],['မရမ်းကုန်','Mayangone','#a95b90'],['ပြည်တွင်းခွန်','DOMESTIC TAX',undefined,'₭'],['ရွှေတောင်ကြား','Shwe Taung Kyar','#a95b90'],['သုဝဏ္ဏ (ဗိုလ်ချုပ်ရွာ)','Thuwunna','#a95b90'],
].map(([my,en,color,icon])=>({my:my!,en:en!,color,icon}));

const panelData={design:[['Sponsor Theme','ဂိမ်းအမည် · လိုဂို','Primary / accent colors','Board background & fonts'],['Board & Properties','မြို့နာမည်၊ အရောင်၊ ပုံ','40-space board appearance','Show / hide property'],['Cards & Tokens','ကံ / ပဟေဠိ 4:3 card design','Token icon 6 ခု','Dice pip and border colors'],['Ads & Media','Sponsor banner slots','Background, logo, assets','Unicode translation content']],flow:[['Money & Buildings','စတင်ငွေ · ကျပ် ၅၀,၀၀၀','ဝယ်ဈေး · ငှားခ','အိမ် / ဟိုတယ်ဆောက်ခ'],['Rules','အကျဉ်းစခန်း · အခွန် · အပေါင်','လေလံ · အရောင်းအဝယ် · ဒေဝါလီ','ကံ / ပဟေဠိ card effects'],['Players & AI','2–6 players · AI settings','60-second turn timer','Disconnect AI takeover'],['Room Flow','Public room / private code','Host controls & game start','Security audit log']]};

function Board({onBack}:{onBack:()=>void}){const [roll,setRoll]=useState<number>();const [step,setStep]=useState(0);const doRoll=()=>{const n=Math.floor(Math.random()*6)+1;setRoll(n);setStep(s=>(s+n)%40)};return <main className="play-shell"><header className="play-head"><button onClick={onBack}>← ထွက်မည်</button><div><b>မြန်မာ မိုနိုပိုလီ</b><span>အခန်း 8K5F2P · Real-time room</span></div><button><Volume2 size={18}/></button></header><section className="game-layout"><div className="board">{spaces.map((s,i)=><div key={i} className={`space space-${i+1}`} style={{'--space-color':s.color||'#caa54a'} as React.CSSProperties}>{s.color&&<span/>}<strong>{s.my}</strong><small>{s.en}</small>{s.icon&&<i>{s.icon}</i>}</div>)}<div className="board-centre"><div>✦</div><p>မြန်မာ့ စီးပွားရေးခရီး</p><h1>မြန်မာ<br/>မိုနိုပိုလီ</h1><span>ခရီး · ပိုင်ဆိုင်မှု · အောင်မြင်မှု</span><section><article>ကံ<br/><b>ကတ်</b></article><article>ပဟေဠိ<br/><b>ကတ်</b></article></section></div><b className="player-piece" style={{left:`${7+step*2.1}%`}}>🐘</b></div><aside className="game-panel"><section><p>လက်ရှိကစားသူ</p><h2>ကိုကို</h2><b>ကျပ် ၅၀,၀၀၀</b><small>နွားလှည်း · Player 1</small></section><section><p>အလှည့် အချိန်</p><strong className="timer">၀:၅၈</strong><small>{roll?`${roll} ကျလာပါသည် — ${spaces[step].my} သို့ ရောက်ရှိသည်`:'သင့်အလှည့်ဖြစ်ပါသည်'}</small></section><button className="dice" onClick={doRoll}><Dice5 size={34}/>အန်စာလှိမ့်မည်{roll&&<b>{roll}</b>}</button><section><p>ကစားသူများ</p><small>🐘 ကိုကို · လက်ရှိအလှည့်</small><small>🛶 မမ</small><small>🐎 ဇော်ဇော် AI</small></section></aside></section></main>}

function Dashboard({onBack}:{onBack:()=>void}){const [tab,setTab]=useState<'design'|'flow'>('design');return <main className="dashboard"><header><button onClick={onBack}>← ပင်မသို့</button><div><Settings2/> Admin Dashboard</div><span><Lock size={14}/> Protected</span></header><nav className="dash-tabs"><button className={tab==='design'?'on':''} onClick={()=>setTab('design')}><Palette/>Game Design</button><button className={tab==='flow'?'on':''} onClick={()=>setTab('flow')}><Settings2/>Game Flow</button></nav><section className="dash-grid">{panelData[tab].map(([title,...items])=><article key={title}><h2>{title}</h2>{items.map(item=><button key={item}>{item}<span>ပြင်မည် →</span></button>)}</article>)}</section></main>}

export default function Home(){const [view,setView]=useState<View>('home');const [name,setName]=useState('');const [confirm,setConfirm]=useState(false);if(view==='board')return <Board onBack={()=>setView('home')}/>;if(view==='dashboard')return <Dashboard onBack={()=>setView('home')}/>;if(view==='lobby')return <main className="lobby"><header className="lobby-head"><button onClick={()=>setView('home')}>← ပြန်မည်</button><b>မြန်မာ မိုနိုပိုလီ</b><button onClick={()=>setView('dashboard')}><Settings2 size={17}/> Dashboard</button></header><section className="lobby-card"><p>PRIVATE GAME · 8K5F2P</p><h1>ကစားသူများ စောင့်နေပါသည်</h1><span>Link သို့မဟုတ် room code ဖြင့် သူငယ်ချင်းများ ဖိတ်ခေါ်ပါ</span><div className="room-code">8 K 5 F 2 P <button>ကူးယူမည်</button></div><div className="lobby-players"><span>🐘 {name||'ကစားသူ'} <b>HOST</b></span><span>🛶 ကစားသူ ဝင်ရန် စောင့်နေသည်</span><span>🐎 AI ထည့်ရန် <button>+ AI</button></span></div><button className="start-game" onClick={()=>setConfirm(true)}><Play fill="currentColor"/>ဂိမ်းစတင်မည်</button></section>{confirm&&<div className="modal"><section><button className="close" onClick={()=>setConfirm(false)}><X/></button><i>✦</i><h2>ဂိမ်းစတင်မလား?</h2><p>ကစားသူများအားလုံးကို အသံဖြင့် အသိပေးမည်။</p><button className="start-game" onClick={()=>setView('board')}>အတည်ပြု၍ စတင်မည်</button></section></div>}</main>;return <main className="home"><nav><b>မြန်မာ မိုနိုပိုလီ</b><button onClick={()=>setView('dashboard')}><Settings2 size={16}/>Admin</button></nav><section className="hero"><p>MYANMAR BOARD GAME · 2–6 PLAYERS</p><h1>မြန်မာ့<br/><span>စီးပွားရေးခရီး</span></h1><em>မြို့များကိုပိုင်ဆိုင်၊ စီးပွားရေးတည်ဆောက်ပြီး အနိုင်ယူပါ</em><div className="join"><label>ကစားသူအမည်<input value={name} onChange={e=>setName(e.target.value)} placeholder="သင့်နာမည် ရေးပါ"/></label><button onClick={()=>setView('lobby')}><Play fill="currentColor"/>ကစားမည်</button></div><section className="room-actions"><button onClick={()=>setView('lobby')}>အခန်းများကြည့်မည်</button><button onClick={()=>setView('lobby')}>Private game ဖန်တီးမည်</button></section></section><aside className="home-rule"><h2>မကစားမီ Rules ကိုကြည့်ပါ</h2><p>Classic Monopoly rules · 60-second turn · disconnect AI takeover</p><button>Rules ကြည့်မည် →</button></aside></main>}
